
services:

  currency-workers:
    build: ./workers/CurrencyWorkers
    image: bank-app/currency-workers
    restart: unless-stopped
    environment:
      - REF_CURRENCY=${REF_CURRENCY?:err}
      - EXCHANGE_RATE_BASE_ROUTE=${EXCHANGE_RATE_BASE_ROUTE:?err}
      - RABBITMQ_CONNECTION_STRING=amqp://rabbitmq-broker:5672
      - EXCHANGE_NAME=currencyRates
      - CURRENCY_POLLING_RATE_IN_MINUTES=${CURRENCY_POLLING_RATE_IN_MINUTES:?err}
      - MONGODB_URL=${ACCOUNTS_MONGODB_URL:?err}
      - SQLDB_CONNECTION_STRING=mysql:${TRANSACTION_MYSQL_DB_USERNAME:?err}:${TRANSACTION_MYSQL_DB_PASSWORD:?err}@mysql-transaction-db/transaction_service_db
    depends_on:
      - transaction-microservice
      - accounts-microservice
      - rabbitmq-broker